# 离线分析脚本的默认输出目录名（与脚本主文件名一致，便于对照）。

OUTPUT_ANALYZE_MACRO_ERRORS = "analyze_macro_errors"
OUTPUT_ANALYZE_MACRO_METADATA = "analyze_macro_metadata"
OUTPUT_ANALYZE_MICRO_ERRORS = "analyze_micro_errors"
OUTPUT_ANALYZE_MICRO_METADATA = "analyze_micro_metadata"

# 兼容旧常量名（分析脚本 import）
OUTPUT_ANALYZE_REGRESSION_ERRORS = OUTPUT_ANALYZE_MACRO_ERRORS
OUTPUT_ANALYZE_REGRESSION_METADATA = OUTPUT_ANALYZE_MACRO_METADATA
OUTPUT_ANALYZE_MULTITASK_ERRORS = OUTPUT_ANALYZE_MICRO_ERRORS
OUTPUT_ANALYZE_MULTITASK_METADATA = OUTPUT_ANALYZE_MICRO_METADATA
